name: AP1 schedules via dify-schedule

on:
  schedule:
    # JST=UTC+9
    # 72h: 毎週火曜 09:10 JST → UTC 00:10 火
    - cron: "10 0 * * 2"
    # 24h: 毎日 09:15 JST → UTC 00:15 毎日
    - cron: "15 0 * * *"
    # 8h: 09:20 JST を起点に 8h毎 → UTC 00:20 / 08:20 / 16:20
    - cron: "20 0 * * *"
    - cron: "20 8 * * *"
    - cron: "20 16 * * *"
    # 4h: 09:25 JST 起点 → UTC 00:25 / 04:25 / 08:25 / 12:25 / 16:25 / 20:25
    - cron: "25 0,4,8,12,16,20 * * *"
  workflow_dispatch: {}  # 手動実行も可能

concurrency:
  group: ap1-${{ github.ref }}
  cancel-in-progress: false

jobs:
  # 共通ステップを再利用するための "composite" 風テンプレ（matrix毎に呼び出す）
  run-scheduler:
    name: Run ${{ matrix.horizon }}h for ${{ matrix.pair }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # === 72h（火曜 09:10 JST のときだけ動かす）===
          - when: "10 0 * * 2"
            horizon: 72
            pair: USDJPY
          - when: "10 0 * * 2"
            horizon: 72
            pair: GBPUSD

          # === 24h（毎日 09:15 JST のときだけ動かす）===
          - when: "15 0 * * *"
            horizon: 24
            pair: USDJPY
          - when: "15 0 * * *"
            horizon: 24
            pair: GBPUSD

          # === 8h（09:20 / 17:20 / 01:20 JST の枠で動かす）===
          - when: "20 0 * * *"
            horizon: 8
            pair: USDJPY
          - when: "20 0 * * *"
            horizon: 8
            pair: GBPUSD
          - when: "20 8 * * *"
            horizon: 8
            pair: USDJPY
          - when: "20 8 * * *"
            horizon: 8
            pair: GBPUSD
          - when: "20 16 * * *"
            horizon: 8
            pair: USDJPY
          - when: "20 16 * * *"
            horizon: 8
            pair: GBPUSD

          # === 4h（09:25 起点の4h毎）===
          - when: "25 0,4,8,12,16,20 * * *"
            horizon: 4
            pair: USDJPY
          - when: "25 0,4,8,12,16,20 * * *"
            horizon: 4
            pair: GBPUSD

    # “今のトリガー（cron）と行が一致するものだけ” を実行
    if: ${{ contains(matrix.when, github.event.schedule || '') || github.event_name == 'workflow_dispatch' }}

    env:
      # === スケジューラ側が読む環境変数 ===
      DIFY_BASE_URL: ${{ secrets.DIFY_BASE_URL }}     # 未設定ならツール側が https://api.dify.ai/v1 を使用
      DIFY_TOKENS:   ${{ secrets.DIFY_TOKENS }}       # ; 区切りで複数可
      # ここで “実行ごとに異なる入力” を JSON で渡す
      DIFY_INPUTS: >-
        {"pair":"${{ matrix.pair }}",
         "horizon_hours":${{ matrix.horizon }},
         "password":"${{ secrets.WORKFLOW_PASSWORD }}",
         "comment":"auto by dify-schedule (${{ matrix.horizon }}h)"}

    steps:
      - name: Checkout dify-schedule
        uses: actions/checkout@v4
        with:
          repository: leochen-g/dify-schedule
          path: dify-schedule

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        working-directory: dify-schedule
        run: npm ci

      - name: Run scheduler
        working-directory: dify-schedule
        env:
          DIFY_BASE_URL: ${{ env.DIFY_BASE_URL }}
          DIFY_TOKENS:   ${{ env.DIFY_TOKENS }}
          DIFY_INPUTS:   ${{ env.DIFY_INPUTS }}
          # ↓ メール通知など追加したい場合は README の通知系ENVをここに並べる
          # EMAIL_USER: ${{ secrets.EMAIL_USER }}
          # EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          # EMAIL_TO:   you@example.com
        run: node index.js
