name: Auto

on:
  schedule:
    # 既定（原作者設定）: 北京時間 06:30 → UTC 22:30
    - cron: "30 22 * * *"
    # 追加: JST=UTC+9
    # 72h: 毎週火曜 09:10 JST → UTC 00:10 火
    - cron: "10 0 * * 2"
    # 24h: 毎日 09:15 JST → UTC 00:15 毎日
    - cron: "15 0 * * *"
    # 8h: JST 09:20 / 17:30 / 23:30 → UTC 00:20 / 08:30 / 14:30
    - cron: "20 0 * * *"
    - cron: "30 8 * * *"
    - cron: "30 14 * * *"
    # 4h: JST 09:25 / 13:00 / 17:00 / 21:00 / 01:00 / 05:00
    #  → UTC 00:25 / 04:00 / 08:00 / 12:00 / 16:00 / 20:00
    - cron: "25 0 * * *"
    - cron: "0 4,8,12,16,20 * * *"
  workflow_dispatch:

env:
  # ── 原リポジトリが読む環境変数（変更不要）
  DIFY_TOKENS: ${{ secrets.DIFY_TOKENS }}
  DIFY_BASE_URL: ${{ secrets.DIFY_BASE_URL }}
  DIFY_INPUTS: ${{ secrets.DIFY_INPUTS }}
  EMAIL_USER: ${{ secrets.EMAIL_USER }}
  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
  EMAIL_TO: ${{ secrets.EMAIL_TO }}
  DINGDING_WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
  PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
  WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}
  SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
  FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
  AIBOTK_KEY: ${{ secrets.AIBOTK_KEY }}
  AIBOTK_ROOM_RECIVER: ${{ secrets.AIBOTK_ROOM_RECIVER }}
  AIBOTK_CONTACT_RECIVER: ${{ secrets.AIBOTK_CONTACT_RECIVER }}

jobs:
  DifyWorkflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout dify-schedule
        uses: actions/checkout@v4
        with:
          repository: leochen-g/dify-schedule
          path: dify-schedule

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        working-directory: dify-schedule
        run: npm ci

      # ▼ ここで “どの cron で起動したか” によって horizon を決定し、
      #    USDJPY / GBPUSD を順に実行。DIFY_INPUTS は “コマンドにインライン付与” する。
      - name: Run per schedule (inject DIFY_INPUTS inline)
        working-directory: dify-schedule
        env:
          SCHEDULE: ${{ github.event.schedule }}
          PASSWORD: ${{ secrets.WORKFLOW_PASSWORD }}
          DIFY_BASE_URL: ${{ env.DIFY_BASE_URL }}
          DIFY_TOKENS:   ${{ env.DIFY_TOKENS }}
        run: |
          set -euo pipefail
          echo "Triggered by schedule: '${SCHEDULE:-manual}'"

          # マッピング：cron → horizon
          H=""
          case "${SCHEDULE:-manual}" in
            "10 0 * * 2") H="72" ;;                                 # Tue 00:10 UTC (JST 09:10)
            "15 0 * * *") H="24" ;;                                 # Daily 00:15 UTC (JST 09:15)
            "20 0 * * *"|"30 8 * * *"|"30 14 * * *") H="8" ;;       # 09:20 / 17:30 / 23:30 JST
            "25 0 * * *"|"0 4,8,12,16,20 * * *") H="4" ;;           # 09:25 から4h毎 JST
            *) echo "No matched schedule → fallback to manual/single-run";;
          esac

          # jq が確実にあるとは限らないので node で JSON を作る関数を用意
          make_inputs() {
            node -e 'const [p,h,pw]=process.argv.slice(1);
                     const o={pair:p,horizon_hours:Number(h),password:pw,
                              comment:`auto by dify-schedule (${h}h)`};
                     process.stdout.write(JSON.stringify(o));' "$@"
          }

          run_one() {
            local PAIR="$1"; local HZ="$2"
            local INP
            INP="$(make_inputs "$PAIR" "$HZ" "${PASSWORD}")"
            echo "→ Run pair=${PAIR} horizon=${HZ}"
            # 重要：DIFY_INPUTS を “コマンド前に1回限りの環境変数” としてインライン付与
            DIFY_INPUTS="${INP}" DIFY_TOKENS="${DIFY_TOKENS}" DIFY_BASE_URL="${DIFY_BASE_URL}" node index.js
          }

          if [ -n "${H}" ]; then
            run_one USDJPY "${H}"
            run_one GBPUSD "${H}"
          else
            # 手動実行や既定枠は env.DIFY_INPUTS をそのまま使って単発実行
            echo "Using env.DIFY_INPUTS as-is (single-run)"
            node index.js
          fi
